module.exports = {
  _: {
    storage_is_encrypted: 'האחסון שלך מוצפן. נדרש סיסמה לפענוח',
    enter_password: 'הכנס סיסמה',
    bad_password: 'סיסמה שגויה, נסה שוב.',
    never: 'לעולם לא',
    continue: 'המשך',
    ok: 'אישור',
    bad_network: "שגיאת חיבור, נסה שוב",
  },
  general: {
    cancel: 'ביטול',
    delete: 'מחק',
    close: 'סגור',
    reply: 'השב',
    reward: 'תגמול',
    other_amount: 'סכום אחר',
    reply_sent: 'תשובה נשלחה',
    offer_sent: 'הצעה נשלחה',
    reward_sent: 'תגמול נשלח',
    share: 'שתף',
    share_sent: 'נשלח בהצלחה',
    copiedToClipboard: 'הועתק ללוח',
    unconfirmed: 'לא מאושר',
    label_wallets: 'ארנקים',
    label_data: 'תוכן',
    label_settings: 'הגדרות',
    label_explore: 'גלה',
    language_restart: 'לאחר בחירת שפה חדשה, יש להפעיל מחדש את האפליקציה כדי שהשינוי ייכנס לתוקף.',
    balance: 'יתרה',
    done: 'בוצע',
    video_too_big: 'קובץ גדול מ-30MB. אנא קיצר או דחס אותו.',
  },
  namespaces: {
    height: "בלוק",
    my_data: "אני",
    others: "מעקב",
    namespace_name: "שם פרופיל",
    name: 'שם',
    shortcode: "קוד קצר",
    shortcode_id: "קוד קצר או מזהה פרופיל",
    search_hashtag: "הכנס תג, למשל return",
    no_data: "אין נתונים",
    click_add_btn: "הקלד שם ולחץ על כפתור '+' ליצירת פרופיל",
    click_search_btn: "הכנס קוד קצר (למשל 5570511) ולחץ על כפתור 'חיפוש'",
    explain: "לא רואה את הפרופילים שלך? גרור למטה לרענון",
    namespace_creation_err: 'לא ניתן ליצור פרופיל.',
    update_key_err: 'לא ניתן לעדכן או להוסיף ערך מפתח.',
    delete_key_err: 'לא ניתן למחוק מפתח.',
    not_enough_fund: 'אין מספיק כספים',
    not_enough_fund_locked: 'אין מספיק כספים. חלק מהכספים ננעלו לרכישה. נסה להוסיף עוד.',
    multiaddress_wallet: 'נתמך רק ארנק עם מספר כתובות.',
    creating_tx: 'יוצר עסקה...',
    please_wait: 'זה ייקח כ-10 שניות.',
    scanning_block: 'מושך נתונים',
    refreshing: 'מרענן נתונים...',
    default_share: 'פוסט מ',
    namespace_unconfirmed: 'הפרופיל טרם אושר',
    hide_namespace: 'להפסיק מעקב?',
    hide: 'הפסק מעקב',
    no_wallet: 'נדרש ארנק עם יתרה',
    create_namespace_first: 'צור פרופיל קודם',
    check_again: 'בדוק שוב',
    pending_confirmation: 'ממתין לאישור. זה ייקח מספר דקות. אתה יכול להתחיל להוסיף תוכן לפרופיל שלך.',
    confirmed: 'הפרופיל אושר',
    no_hashtag: 'אין תוצאות עבור ',
    hashtag_help: 'חפש תגיות\nראה מה טרנדי עכשיו',
    submit: 'שלח',
    title: 'כותרת',
    content: 'תוכן',
    follow: 'עקוב',
    following: 'מעקב',
    comment_post: 'הגיב לפוסט',
    share_post: 'שיתף פוסט',
    reward_post: 'תגמל פוסט',
    update_profile: 'הפרופיל עודכן',
    created: 'הפרופיל נוצר',
    namespace_not_found: 'לא ניתן למצוא פרופיל',
    ns_transfer_explain: 'העברה לארנק אחר',
    ns_transfer_notes: 'הערות',
    sell_nft: 'מכור כ-NFT',
    edit: 'ערוך',
    manage: 'נהל',
    asking_price: 'מחיר המכירה: ',
    nft_desc: 'תיאור ה-NFT שלך',
    buy_it: 'קנה',
    make_offer: 'הצע הצעה',
    bid_price: 'מחיר ההצעה',
    for_sale: 'למכירה',
    cancel_sale: "בטל מכירה",
    confirm: 'אשר',
    add_post: 'הוסף',
    qr_error: 'תוכן לא תקין. חסר מפתח או ערך.',
    qr_json_error: 'פורמט JSON לא תקין.',
  },
  wallets: {
    select_wallet: 'בחר ארנק',
    options: 'אפשרויות',
    createBitcoinWallet:
      'אין לך כרגע ארנק Kevacoin. כדי לממן ארנק Lightning, יש ליצור או לייבא ארנק Kevacoin. האם תרצה להמשיך בכל מקרה?',
    list: {
      app_name: 'KevaWallet',
      title: 'ארנקים',
      header: 'ארנק מייצג זוג של סוד (מפתח פרטי) וכתובת' + 'שאתה יכול לשתף כדי לקבל מטבעות.',
      add: 'הוסף ארנק',
      create_a_wallet: 'הוסף ארנק',
      create_a_wallet1: "זה חינמי ואתה יכול ליצור",
      create_a_wallet2: 'כמה שתרצה',
      create_a_button: 'הוסף עכשיו',
      latest_transaction: 'עסקה אחרונה',
      empty_txs1: 'העסקאות שלך יופיעו כאן',
      empty_txs2: 'התחל עם הארנק שלך',
      empty_txs1_lightning:
        'ארנק Lightning צריך לשמש לעסקאות היומיומיות שלך. העמלות זולות מאוד והמהירות מהירה במיוחד.',
      empty_txs2_lightning: '\nכדי להתחיל להשתמש בו, לחץ על "נהל כספים" והזן את היתרה שלך.',
      tap_here_to_buy: 'לחץ כאן לרכישת Kevacoin',
      single_address: 'כתובת יחידה',
      hd_multi_address: 'כתובות מרובות HD',
    },
    reorder: {
      title: 'סדר מחדש ארנקים',
    },
    add: {
      title: 'הוסף ארנק',
      description:
        'אתה יכול לסרוק גיבוי ארנק נייר (בפורמט WIF - Wallet Import Format), או ליצור ארנק חדש. ארנקי Segwit נתמכים כברירת מחדל.',
      scan: 'סרוק',
      create: 'צור',
      label_new_segwit: 'SegWit חדש',
      label_new_lightning: 'Lightning חדש',
      wallet_name: 'שם',
      wallet_type: 'סוג',
      or: 'או',
      import_wallet: 'ייבא ארנק',
      imported: 'מיובא',
      coming_soon: 'בקרוב',
      lightning: 'Lightning',
      bitcoin: 'Kevacoin',
      multi_address: 'כתובות מרובות',
      single_address: 'כתובת יחידה',
    },
    details: {
      title: 'ארנק',
      address: 'כתובת',
      master_fingerprint: 'טביעת אצבע ראשית',
      type: 'סוג',
      label: 'תווית',
      destination: 'יעד',
      description: 'תיאור',
      are_you_sure: 'האם אתה בטוח?',
      yes_delete: 'כן, מחק',
      no_cancel: 'לא, בטל',
      delete: 'מחק',
      save: 'שמור',
      delete_this_wallet: 'מחק ארנק זה',
      export_backup: 'ייצא / גבה',
      buy_bitcoin: 'קנה Kevacoin',
      show_xpub: 'הצג XPUB של הארנק',
      connected_to: 'מחובר ל',
      advanced: 'מתקדם',
      use_with_hardware_wallet: 'השתמש עם ארנק חומרה',
    },
    export: {
      title: 'ייצוא ארנק',
    },
    xpub: {
      title: 'XPUB של הארנק',
      copiedToClipboard: 'הועתק ללוח.',
    },
    import: {
      title: 'ייבא',
      explanation:
        "כתוב כאן את המילים שלך, מפתח פרטי, WIF, או כל דבר אחר שיש לך. KevaWallet ינסה לנחש את הפורמט הנכון ולייבא את הארנק שלך",
      imported: 'מיובא',
      error: 'ייצוא נכשל. אנא וודא שהנתונים שסופקו תקינים.',
      success: 'הצלחה',
      do_import: 'ייבא',
      scan_qr: 'סרוק או ייבא קובץ',
    },
    scanQrWif: {
      go_back: 'חזור',
      cancel: 'ביטול',
      decoding: 'מפענח',
      input_password: 'הכנס סיסמה',
      password_explain: 'זה מפתח פרטי מוצפן BIP38',
      bad_password: 'סיסמה שגויה',
      wallet_already_exists: 'ארנק כזה כבר קיים',
      bad_wif: 'WIF שגוי',
      imported_wif: 'WIF מיובא ',
      with_address: ' עם כתובת ',
      imported_segwit: 'SegWit מיובא',
      imported_legacy: 'Legacy מיובא',
      imported_watchonly: 'צפייה בלבד מיובא',
    },
  },
  transactions: {
    list: {
      tabBarLabel: 'עסקאות',
      title: 'עסקאות',
      description: 'רשימת עסקאות נכנסות או יוצאות מארנקיך',
      conf: 'אישור',
    },
    details: {
      title: 'עסקה',
      from: 'קלט',
      to: 'פלט',
      copy: 'העתק',
      transaction_details: 'פרטי עסקה',
      show_in_block_explorer: 'צפה בבלוק אקספלורר',
    },
  },
  send: {
    header: 'שלח',
    details: {
      title: 'צור עסקה',
      amount_field_is_not_valid: 'שדה הסכום לא תקין',
      fee_field_is_not_valid: 'שדה העמלה לא תקין',
      address_field_is_not_valid: 'שדה הכתובת לא תקין',
      total_exceeds_balance: 'סכום השליחה חורג מהיתרה הזמינה.',
      create_tx_error: 'אירעה שגיאה ביצירת העסקה. אנא וודא שהכתובת תקינה.',
      address: 'כתובת',
      amount_placeholder: 'סכום לשליחה (ב-BTC)',
      fee_placeholder: 'פלוס עמלת עסקה (ב-BTC)',
      note_placeholder: 'הערה לעצמי',
      cancel: 'ביטול',
      scan: 'סרוק',
      send: 'שלח',
      create: 'צור חשבונית',
      remaining_balance: 'יתרה נותרת',
    },
    confirm: {
      header: 'אשר',
      sendNow: 'שלח עכשיו',
    },
    success: {
      done: 'בוצע',
    },
    create: {
      details: 'פרטים',
      title: 'צור עסקה',
      error: 'שגיאה ביצירת עסקה. כתובת או סכום שליחה לא תקינים?',
      go_back: 'חזור',
      this_is_hex: `זה ה-hex של העסקה שלך, חתום ומוכן לשידור לרשת.`,
      to: 'אל',
      amount: 'סכום',
      fee: 'עמלה',
      tx_size: 'גודל TX',
      satoshi_per_byte: 'סאטושי לבייט',
      memo: 'תזכורת',
      broadcast: 'שדר',
      not_enough_fee: 'אין מספיק עמלה. הגדל את העמלה',
    },
  },
  receive: {
    header: 'קבל',
    details: {
      title: 'שתף את הכתובת הזו עם המשלם',
      share: 'שתף',
      copiedToClipboard: 'הועתק ללוח.',
      label: 'תיאור',
      create: 'צור',
      setAmount: 'קבל עם סכום',
    },
    scan_lnurl: 'סרוק לקבלה',
  },
  buyBitcoin: {
    header: 'קנה Kevacoin',
    tap_your_address: 'לחץ על הכתובת שלך להעתקה ללוח:',
    copied: 'הועתק ללוח!',
  },
  settings: {
    general: 'כללי',
    security: 'אבטחה',
    header: 'הגדרות',
    plausible_deniability: 'הכחשה מתקבלת על הדעת',
    storage_not_encrypted: 'אחסון: לא מוצפן',
    storage_encrypted: 'אחסון: מוצפן',
    password: 'סיסמה',
    password_explain: 'צור את הסיסמה שתשתמש בה לפענוח האחסון',
    retype_password: 'הקלד שוב סיסמה',
    passwords_do_not_match: 'הסיסמאות אינן תואמות',
    encrypt_storage: 'הצפן אחסון',
    lightning_settings: 'הגדרות Lightning',
    lightning_settings_explain:
      'כדי להתחבר ל-LND node שלך, אנא התקן LndHub' +
      " והכנס את ה-URL שלו כאן בהגדרות. השאר ריק כדי להשתמש ב-LNDHub של KevaWallet (lndhub.io). ארנקים שנוצרו לאחר שמירת השינויים יתחברו ל-LNDHub שצוין.",
    network: 'רשת',
    electrum_settings: 'הגדרות Electrum',
    electrum_settings_explain: 'הגדר לריק לשימוש בברירת מחדל',
    electrum_restart: 'השינויים שלך נשמרו בהצלחה. ייתכן שיידרש הפעלה מחדש כדי שהשינויים ייכנסו לתוקף.',
    save: 'שמור',
    about: 'אודות',
    language: 'שפה',
    currency: 'מטבע',
    advanced_options: 'אפשרויות מתקדמות',
    enable_advanced_mode: 'מצב מתקדם',
    advanced_mode_note: 'כאשר מופעל, תוכל לצפות בארנקים ובעסקאות נבחרות באמצעות מכשירי Apple iCloud המחוברים האחרים שלך.',
    ipfs_settings: 'הגדרות IPFS',
    ipfs_settings_explain: 'השתמש בשער IPFS מותאם אישית',
    ipfs_error_0: "לא רואה תמונה?",
    ipfs_error_1: 'שנה שער IPFS',
    ipfs_error_2: 'הגדרות -> רשת -> הגדרות IPFS',
  },
  plausibledeniability: {
    title: 'הכחשה מתקבלת על הדעת',
    help:
      'בנסיבות מסוימות, ייתכן שתיאלץ לחשוף ' +
      'סיסמה. כדי לשמור על המטבעות שלך בטוחים, KevaWallet יכול ליצור ' +
      'אחסון מוצפן נוסף, עם סיסמה שונה. תחת לחץ, ' +
      'אתה יכול לחשוף את הסיסמה הזו לצד שלישי. אם מוזן ' +
      "ב-KevaWallet, זה יפתח 'אחסון מזויף' חדש. זה יראה " +
      'לגיטימי לצד שלישי, אבל זה ישמור בסתר על האחסון העיקרי שלך ' +
      'עם מטבעות בטוחים.',
    help2: 'האחסון החדש יהיה פונקציונלי לחלוטין, ותוכל לשמור שם ' + 'סכומים מינימליים כדי שיראה יותר אמין.',
    create_fake_storage: 'צור אחסון מוצפן',
    go_back: 'חזור',
    create_password: 'צור סיסמה',
    create_password_explanation: 'הסיסמה לאחסון מזויף לא צריכה להתאים לסיסמה לאחסון העיקרי שלך',
    password_should_not_match: 'הסיסמה כבר בשימוש. אנא נסה סיסמה אחרת.',
    retype_password: 'הקלד שוב סיסמה',
    passwords_do_not_match: 'הסיסמאות אינן תואמות, נסה שוב',
    success: 'הצלחה',
  },
  lnd: {
    title: 'נהל כספים',
    choose_source_wallet: 'בחר ארנק מקור',
    refill_lnd_balance: 'תסף יתרה בארנק Lightning',
    refill: 'תסף',
    withdraw: 'משוך',
    expired: 'פג תוקף',
    placeholder: 'חשבונית',
    sameWalletAsInvoiceError: 'אינך יכול לשלם חשבונית עם אותו ארנק שבו השתמשת ליצירתה.',
  },
  pleasebackup: {
    title: 'הארנק שלך נוצר...',
    text:
      "אנא קח רגע לרשום את המילים האלה על פיסת נייר. זה הגיבוי שלך שתוכל להשתמש בו לשחזור הארנק במכשיר אחר.",
    ok: 'אוקיי, רשמתי את זה!',
  },
  lndViewInvoice: {
    wasnt_paid_and_expired: 'החשבונית הזו לא שולמה ותוקפה פג',
    has_been_paid: 'החשבונית הזו שולמה',
    please_pay: 'אנא שלם',
    sats: 'סאטושי',
    for: 'עבור:',
    additional_info: 'מידע נוסף',
    open_direct_channel: 'פתח ערוץ ישיר עם הצומת הזה:',
  },
}; 